---

include:
  - project: public-isg/pipelines
    ref: main
    file:
      - deploy-docker-image.yml
      - deploy-helm-chart.yml

stages:
  - docker
  - helm

# Testing versions like: v2.739rc35 -> v2.739rc35, v2.739rc, v2rc, testing / v32.0rc1 -> v32.0rc1, v32.0rc, v32rc, testing
deploy-docker-image-test:
  extends: .deploy-docker-image
  stage: docker
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+rc[0-9]+$/'
  variables:
    DOCKER_TAG: "testing"
  before_script:
    - export DOCKER_BUILD_ARG="version=${CI_COMMIT_TAG}"
    - export DOCKER_TAG_ADDITIONAL1="${CI_COMMIT_TAG%%rc*}rc"
    - export DOCKER_TAG_ADDITIONAL2="${CI_COMMIT_TAG%.*}rc"

# Production versions like: v8.23 -> v8.23, v8, latest / v3.0 -> v3.0, v3, latest
deploy-docker-image-prod:
  extends: .deploy-docker-image
  stage: docker
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+$/'
  variables:
    DOCKER_TAG: "latest"
  before_script:
    - export DOCKER_BUILD_ARG="version=${CI_COMMIT_TAG}"
    - export DOCKER_TAG_ADDITIONAL1="${CI_COMMIT_TAG%%.*}"

deploy-helm-chart:
  extends: .deploy-helm-chart
  stage: helm
  rules:
    - changes: ["helm/**/*"]
