{{- if .Values.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-files
  labels:
    app: {{ include "name" . }}
    chart: {{ include "chart" . }}
data:
  {{- range $key, $val := .Values.files }}
  {{ $key }}: |-
{{ $.Files.Get (printf "files/%s" $key) | indent 4 }}
  {{- end }}
{{- end }}
