---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-configmap
data:
  {{- range $key, $val := $.Values.files }}
  {{ $key }}: |-
{{ $file := print "files/" $key }}{{ $.Files.Get $file | indent 4 }}
  {{- end }}
