apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "name" . }}
    chart: {{ include "chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ include "name" . }}
  template:
    metadata:
      labels:
        app: {{ include "name" . }}
      annotations:
        # Roll the pods when the secret or files change
        checksum/env: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.files }}
        checksum/files: {{ tpl (toYaml .Values.files) . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      containers:
        - name: {{ include "fullname" . }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop: [ALL]
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.args }}
          args:
          {{- range $arg := $.Values.args }}
            - {{ $arg | quote }}
          {{- end }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "fullname" . }}-env
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
            timeoutSeconds: 5
            failureThreshold: 2
            periodSeconds: 300
          startupProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 2
            failureThreshold: 20
            periodSeconds: 3
          lifecycle:
            preStop:
              exec:
                # Give the load balancer time to remove the
                # pod before terminating (for zero downtime)
                command: ["/bin/sh", "-c", "sleep 20"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: repo
              mountPath: /repo
            - name: tmp
              mountPath: /tmp
            {{- range $key, $val := .Values.files }}
            - name: files
              subPath: {{ $key }}
              mountPath: {{ $val }}
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: repo
          emptyDir:
            medium: Memory
        - name: tmp
          emptyDir: {}
        {{- if .Values.files }}
        - name: files
          configMap:
            name: {{ include "fullname" . }}-files
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
