apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "name" . }}
    chart: {{ include "chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ include "name" . }}
  template:
    metadata:
      labels:
        app: {{ include "name" . }}
      annotations:
        # Roll the pods when the secret or specs change
        {{- if or .Values.env .Values.customEnv }}
        checksum/env: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.specs }}
        checksum/specs: {{ .Values.specs | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      containers:
        - name: {{ include "fullname" . }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop: [ALL]
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.args }}
          args:
          {{- range $arg := $.Values.args }}
            - {{ $arg | quote }}
          {{- end }}
          {{- end }}
          env:
            - name: YAC_ROOT_PATH
              value: {{ include "rootPath" . | quote }}
            - name: YAC_FORMAT_PLUGIN
              value: "json_lines"
            {{- if .Values.redis.enabled }}
            - name: YAC_ENV__REDIS_URL
              value: {{ include "redisUrl" . | quote }}
            {{- end }}
          {{- if or (or .Values.env .Values.customEnv) .Values.extraEnvSecret }}
          envFrom:
            {{- if or .Values.env .Values.customEnv }}
            - secretRef:
                name: {{ include "fullname" . }}-env
            {{- end }}
            {{- if .Values.extraEnvSecret }}
            - secretRef:
                name: {{ .Values.extraEnvSecret }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
            timeoutSeconds: 5
            failureThreshold: 2
            periodSeconds: 300
          startupProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 2
            failureThreshold: 20
            periodSeconds: 3
          lifecycle:
            preStop:
              exec:
                # Give the load balancer time to remove the
                # pod before terminating (for zero downtime)
                command: ["/bin/sh", "-c", "sleep 20"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: repo
              mountPath: /repo
            - name: tmp
              mountPath: /tmp
            {{- if .Values.specs }}
            - name: specs
              subPath: yac.yml
              mountPath: /yac.yml
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: repo
          emptyDir:
            medium: Memory
        - name: tmp
          emptyDir: {}
        {{- if .Values.specs }}
        - name: specs
          configMap:
            name: {{ include "fullname" . }}-specs
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
