{{- if and .Values.redis.enabled (eq (.Values.redis.mode | default "single") "single") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redisName" . }}
  labels:
    app: {{ include "name" . }}
    component: redis
    chart: {{ include "chart" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "name" . }}
    component: redis
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
{{- end }}
