{{- if or .Values.env .Values.customEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-env
  labels:
    app: {{ include "name" . }}
    chart: {{ include "chart" . }}
  {{- with .Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  # User-defined extra YAC_* vars
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

  # Custom env vars (specs `env.<key>`)
  {{- range $key, $val := .Values.customEnv }}
  YAC_ENV__{{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
