apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-env
  labels:
    app: {{ include "name" . }}
    chart: {{ include "chart" . }}
  {{- with .Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  # Static / derived
  YAC_ROOT_PATH: {{ include "rootPath" . | quote }}
  YAC_FORMAT_PLUGIN: "json_lines"

  # OIDC
  YAC_OIDC_URL: {{ .Values.oidc.url | quote }}
  YAC_OIDC_CLIENT_IDS: {{ join "," .Values.oidc.clientIds | quote }}
  YAC_OIDC_JWT_NAME: {{ .Values.oidc.jwt.name | quote }}
  YAC_OIDC_JWT_FULL_NAME: {{ .Values.oidc.jwt.fullName | quote }}
  YAC_OIDC_JWT_FULL_NAME_FALLBACK: {{ .Values.oidc.jwt.fullNameFallback | quote }}
  YAC_OIDC_JWT_EMAIL: {{ .Values.oidc.jwt.email | quote }}
  YAC_OIDC_JWT_EMAIL_FALLBACK: {{ .Values.oidc.jwt.emailFallback | quote }}

  # CORS
  YAC_CORS_ORIGINS: {{ join "," .Values.corsOrigins | quote }}

  # User-defined extra YAC_* vars
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

  # Custom env vars (specs `env.<key>`)
  {{- range $key, $val := .Values.customEnv }}
  YAC_ENV__{{ $key }}: {{ $val | quote }}
  {{- end }}
