"""
Tests for `validator.incoming_new_data` / `incoming_new_yaml`, focusing on the
`UpdateEntity.yaml_base` merge base: a form edit should be merged into the YAML
the client is editing (preserving its comments / anchors / formatting) instead of
the stored entity.
"""

from app.lib import validator
from app.model.inp import OperationRequest, UpdateEntity
from app.model.int import Entity
from app.model.out import User


def _update_op(data, *, yaml_base=None, operation="change", name="name1"):
    return OperationRequest(
        request_headers={},
        request_ip="",
        user=User(name="u", email="u@example.com", full_name="U"),
        operation=operation,
        type="type1",
        name=name,
        actions=[],
        entity=UpdateEntity(name=name, data=data, yaml_base=yaml_base),
    )


STORED = """---
# stored header
owner: Bender # who owns it
ram: 4
"""

# The stored YAML plus session-only edits a user made in the YAML editor:
# an inline comment and an anchor/alias pair that have no data-model footprint.
EDITED = """---
# stored header
owner: Bender # who owns it
ram: 4 # my session note
nodes: &n
  - a
  - b
backup: *n
"""


def _old():
    return Entity(name="name1", exists=True, yaml=STORED, data={"owner": "Bender", "ram": 4})


def test_yaml_base_preserves_session_comments_and_anchors():
    out = validator.incoming_new_yaml(_update_op({"ram": 8}, yaml_base=EDITED), _old())
    assert out is not None
    assert "ram: 8" in out  # the form patch is applied
    assert "# my session note" in out  # session-added inline comment kept
    assert "&n" in out and "*n" in out  # anchor + alias kept
    assert "# stored header" in out  # original comment kept


def test_without_base_falls_back_to_stored_yaml():
    out = validator.incoming_new_yaml(_update_op({"ram": 8}), _old())
    assert out is not None
    assert "ram: 8" in out
    assert "# who owns it" in out  # stored comment survives (stored YAML is the base)
    assert "# my session note" not in out  # session edits are not in the base


def test_create_with_base_keeps_template_comments():
    template = "---\n# Automatically generated by VAYS\n\nowner: null\nram: 4\n"
    op = _update_op({"owner": "Leela", "ram": 8}, yaml_base=template, operation="create")
    out = validator.incoming_new_yaml(op, Entity(name=None, exists=False))
    assert out is not None
    assert "# Automatically generated by VAYS" in out
    assert "owner: Leela" in out
    assert "ram: 8" in out


def test_incoming_new_data_merges_patch_into_base():
    data, err = validator.incoming_new_data(_update_op({"ram": 8}, yaml_base=EDITED), _old())
    assert err is None
    assert data["ram"] == 8  # patched
    assert data["owner"] == "Bender"  # from base
    assert data["nodes"] == ["a", "b"]  # anchor target
    assert data["backup"] == ["a", "b"]  # alias resolves to the same value
