"""
Tests for `validator.incoming_new_data` / `incoming_new_yaml`, focusing on the
`UpdateEntity.yaml_base` merge base: a form edit should be merged into the YAML
the client is editing (preserving its comments / anchors / formatting) instead of
the stored entity.
"""

from app.lib import validator
from app.model.inp import (
    CopyEntity,
    LinkEntity,
    NewEntity,
    OperationRequest,
    ReplaceEntity,
    UpdateEntity,
)
from app.model.int import Entity
from app.model.out import User


def _op(entity, *, operation="create", name=None):
    return OperationRequest(
        request_headers={},
        request_ip="",
        user=User(name="u", email="u@example.com", full_name="U"),
        operation=operation,
        type="type1",
        name=name,
        actions=[],
        entity=entity,
    )


def _update_op(data, *, yaml_base=None, operation="change", name="name1"):
    return OperationRequest(
        request_headers={},
        request_ip="",
        user=User(name="u", email="u@example.com", full_name="U"),
        operation=operation,
        type="type1",
        name=name,
        actions=[],
        entity=UpdateEntity(name=name, data=data, yaml_base=yaml_base),
    )


STORED = """---
# stored header
owner: Bender # who owns it
ram: 4
"""

# The stored YAML plus session-only edits a user made in the YAML editor:
# an inline comment and an anchor/alias pair that have no data-model footprint.
EDITED = """---
# stored header
owner: Bender # who owns it
ram: 4 # my session note
nodes: &n
  - a
  - b
backup: *n
"""


def _old():
    return Entity(name="name1", exists=True, yaml=STORED, data={"owner": "Bender", "ram": 4})


def test_yaml_base_preserves_session_comments_and_anchors():
    out = validator.incoming_new_yaml(_update_op({"ram": 8}, yaml_base=EDITED), _old())
    assert out is not None
    assert "ram: 8" in out  # the form patch is applied
    assert "# my session note" in out  # session-added inline comment kept
    assert "&n" in out and "*n" in out  # anchor + alias kept
    assert "# stored header" in out  # original comment kept


def test_without_base_falls_back_to_stored_yaml():
    out = validator.incoming_new_yaml(_update_op({"ram": 8}), _old())
    assert out is not None
    assert "ram: 8" in out
    assert "# who owns it" in out  # stored comment survives (stored YAML is the base)
    assert "# my session note" not in out  # session edits are not in the base


def test_create_with_base_keeps_template_comments():
    template = "---\n# Automatically generated by VAYS\n\nowner: null\nram: 4\n"
    op = _update_op({"owner": "Leela", "ram": 8}, yaml_base=template, operation="create")
    out = validator.incoming_new_yaml(op, Entity(name=None, exists=False))
    assert out is not None
    assert "# Automatically generated by VAYS" in out
    assert "owner: Leela" in out
    assert "ram: 8" in out


def test_incoming_new_data_merges_patch_into_base():
    data, err = validator.incoming_new_data(_update_op({"ram": 8}, yaml_base=EDITED), _old())
    assert err is None
    assert data["ram"] == 8  # patched
    assert data["owner"] == "Bender"  # from base
    assert data["nodes"] == ["a", "b"]  # anchor target
    assert data["backup"] == ["a", "b"]  # alias resolves to the same value


# ----- other entity kinds + error paths -----

_SRC = Entity(name="src", exists=True, yaml="owner: Bender\n", data={"owner": "Bender"})


def test_new_entity_normalizes_yaml_and_parses_data():
    op = _op(NewEntity(name="x", yaml="ram: 8\n"))
    data, err = validator.incoming_new_data(op, Entity(name=None, exists=False))
    assert err is None and data == {"ram": 8}
    # incoming_new_yaml round-trips through ruamel (explicit start marker).
    assert validator.incoming_new_yaml(op, Entity(name=None, exists=False)) == "---\nram: 8\n"


def test_copy_and_link_inherit_source_data_and_have_no_yaml():
    for entity in (CopyEntity(name="x", copy="src"), LinkEntity(name="x", link="src")):
        op = _op(entity)
        data, err = validator.incoming_new_data(op, _SRC)
        assert err is None and data == {"owner": "Bender"}  # inherits the source
        assert validator.incoming_new_yaml(op, _SRC) is None  # copies/links produce no YAML


def test_replace_entity_uses_yaml_new():
    op = _op(ReplaceEntity(name="x", yaml_old="a: 1\n", yaml_new="a: 2\n"),
             operation="change", name="x")
    data, err = validator.incoming_new_data(op, _SRC)
    assert err is None and data == {"a": 2}
    assert validator.incoming_new_yaml(op, _SRC) == "---\na: 2\n"


def test_malformed_yaml_reports_error_and_no_yaml():
    op = _op(NewEntity(name="x", yaml="a: : : bad"))
    data, err = validator.incoming_new_data(op, Entity(name=None, exists=False))
    assert data == {} and err is not None  # surfaced, not raised
    assert validator.incoming_new_yaml(op, Entity(name=None, exists=False)) is None


def test_read_and_delete_use_stored_data():
    assert validator.incoming_new_data(_op(None, operation="read", name="src"), _SRC) == (
        {"owner": "Bender"}, None
    )
    # delete (no entity payload, not a read) yields empty new-data.
    assert validator.incoming_new_data(_op(None, operation="delete", name="src"), _SRC) == (
        {}, None
    )


# ----- test_all / test_ls orchestration -----
# These drive the full validator pipeline (schema generation + the built-in
# validator plugins + limit enforcement) against a minimal but complete Specs.

from app.lib import validator as _v  # noqa: E402
from app.model.spc import Specs, Type, Request as SpcRequest, Sets, Repo  # noqa: E402
from app.model.spc import Schema as SpcSchema  # noqa: E402
from app.model.err import RequestError  # noqa: E402
from app import consts  # noqa: E402

import pytest  # noqa: E402


def _full_specs(schema_dict=None):
    typ = Type.model_construct(
        name="type1", title="T", name_pattern=consts.NAME_PATTERN,
        create=True, change=True, delete=True, options=[], logs=[], actions=[],
        favorites=[], limits=[], name_generated="never", name_generator="uuid()",
    )
    return Specs.model_construct(
        types=[typ], type=typ, roles=[], sets=Sets(), request=SpcRequest(),
        context={}, repo=Repo(), json_schema=SpcSchema.model_validate(schema_dict or {}),
    )


def _read_op(name="name1"):
    return OperationRequest(
        request_headers={}, request_ip="1.2.3.4",
        user=User(name="u", email="u@x.com", full_name="U"),
        operation="read", type="type1", name=name, actions=[], entity=None,
    )


async def test_all_read_happy_path():
    old = Entity(name="name1", exists=True, yaml="cpu: 4", data={"cpu": 4})
    res = await _v.test_all(
        _read_op(), _full_specs(), old, Entity(name=None), perms=["see"],
        usages=[], raise_on_error=False,
    )
    assert res.request.valid is True
    # read without schema_on_read -> trivial valid schema
    assert res.schemas.valid is True


async def test_all_malformed_yaml_raises():
    op = _op(NewEntity(name="name1", yaml="a: : : bad"), name="name1")
    with pytest.raises(RequestError):
        await _v.test_all(
            op, _full_specs(), Entity(name=None), Entity(name="name1"),
            perms=["add"], raise_on_error=True,
        )


async def test_all_missing_perm_sets_invalid_without_raising():
    old = Entity(name="name1", exists=True, yaml="cpu: 4", data={"cpu": 4})
    res = await _v.test_all(
        _read_op(), _full_specs(), old, Entity(name=None), perms=[],  # no 'see'
        usages=[], raise_on_error=False,
    )
    assert res.request.valid is False
    assert "see" in res.request.message


async def test_all_invalid_schema_raises_on_change():
    old = Entity(name="name1", exists=True, yaml="cpu: 4", data={"cpu": 4})
    op = OperationRequest(
        request_headers={}, request_ip="1.2.3.4",
        user=User(name="u", email="u@x.com", full_name="U"),
        operation="change", type="type1", name="name1", actions=[],
        entity=NewEntity(name="name1", yaml="cpu: not-an-int"),
    )
    specs = _full_specs(
        {"type": "object",
         "properties": {"cpu": {"type": "integer", "vays_category": "X"}}}
    )
    with pytest.raises(RequestError):
        await _v.test_all(op, specs, old, Entity(name="name1"), perms=["edt"],
                          raise_on_error=True)


_INT_CPU_SCHEMA = {
    "type": "object",
    "properties": {"cpu": {"type": "integer", "vays_category": "X"}},
}


def _change_op(entity):
    return OperationRequest(
        request_headers={}, request_ip="1.2.3.4",
        user=User(name="u", email="u@x.com", full_name="U"),
        operation="change", type="type1", name="name1", actions=[],
        entity=entity,
    )


async def test_all_pure_rename_skips_data_revalidation():
    # The stored data is invalid against the current schema; a pure rename
    # moves the YAML as-is and must not be blocked by that. The (true)
    # validity is still reported in the result, just not enforced.
    old = Entity(name="name1", exists=True, yaml="cpu: not-an-int",
                 data={"cpu": "not-an-int"})
    op = _change_op(UpdateEntity(name="name2", data={}))
    res = await _v.test_all(
        op, _full_specs(_INT_CPU_SCHEMA), old, Entity(name="name2", exists=False),
        perms=["see", "add", "rnm"], raise_on_error=True,
    )
    assert res.schemas.valid is False


async def test_all_pure_rename_via_replace_skips_data_revalidation():
    old = Entity(name="name1", exists=True, yaml="cpu: not-an-int",
                 data={"cpu": "not-an-int"})
    op = _change_op(ReplaceEntity(name="name2", yaml_old="cpu: not-an-int",
                                  yaml_new="cpu: not-an-int"))
    res = await _v.test_all(
        op, _full_specs(_INT_CPU_SCHEMA), old, Entity(name="name2", exists=False),
        perms=["see", "add", "rnm"], raise_on_error=True,
    )
    assert res.schemas.valid is False


async def test_all_rename_with_content_changes_still_revalidates():
    old = Entity(name="name1", exists=True, yaml="cpu: 4", data={"cpu": 4})
    op = _change_op(UpdateEntity(name="name2", data={"cpu": "not-an-int"}))
    with pytest.raises(RequestError):
        await _v.test_all(
            op, _full_specs(_INT_CPU_SCHEMA), old,
            Entity(name="name2", exists=False),
            perms=["see", "add", "rnm", "edt"], raise_on_error=True,
        )


async def test_ls_passes_for_valid_list_request():
    # test_ls runs the list-time validators (names/operations/type_spec) and
    # returns None when nothing is wrong.
    assert await _v.test_ls(_read_op(), _full_specs()) is None
